import type { Metadata } from "next";
import StyledComponentsRegistry from "@/app/styled-components-registry";
import MyLayout from "@/app/my-layout";
import "@/app/index.css";

export const metadata: Metadata = {
  title: "Range component",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "sans-serif" }}>
        <StyledComponentsRegistry>
          <MyLayout>{children}</MyLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
